/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl3.tests

import com.google.inject.Inject
import com.google.inject.Provider
import org.eclipse.xtext.generator.InMemoryFileSystemAccess
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.xtext.example.mydsl3.myDsl.Domainmodel
import org.eclipse.xtext.generator.IGenerator2
import org.eclipse.xtext.generator.GeneratorContext

@RunWith(XtextRunner)
@InjectWith(MyDslInjectorProvider)
class MyDslParsingTest{

	@Inject
	ParseHelper<Domainmodel> parseHelper
	
	@Inject
	Provider<InMemoryFileSystemAccess> fsaP
	
	@Inject
	IGenerator2 generator

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			blog {
				
				title = A-B-C
				, date = 1-1-1
			}

		''')
		Assert.assertNotNull(result)
		val fsa = fsaP.get
		generator.doGenerate(result.eResource, fsa, new GeneratorContext)
		println(fsa.allFiles)
	}

}
